#!/bin/bash

readonly OUTPUT_DIR="${OUTPUT_DIR:-public}"
readonly INDEX_FILE="$OUTPUT_DIR/index.html"

cat > "$INDEX_FILE" <<'HTML'
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Index</title>
  <style>
    ul { line-height: 1.6; }
    li { margin-left: 1em; }
  </style>
</head>
<body>
<h1>Index</h1>
<ul>
HTML

find "$OUTPUT_DIR" -type f \
  ! -name index.html \
  | sed "s|^$OUTPUT_DIR/||" \
  | sort \
  | while read -r f; do
      echo "<li><a href=\"$f\">$f</a></li>" >> "$INDEX_FILE"
    done

cat >> "$INDEX_FILE" <<'HTML'
</ul>
</body>
</html>
HTML
